### ISSUE TITLE
More detailed results that can be shared?

### ISSUE THREAD

**Issue by kmn1024** [efthymisgeo/regotron#1]
Congratulations on the nice results! I have been playing around with Tacotron2 for a bit, and found that in the original implementation, lower losses do not at all imply better alignment.

Wondering if the authors have a bit more results that can be shared. Specifically:
1. In the paper, it was mentioned that "regularized version better stabilizes the training procedure when weighted appropriately, λ ∈ {10−3, 10−4, 10−5}". What do the loss curves look like for different values of λ?
2. Do you have a series of alignment plots (similar to Figure 2) that demonstrates how alignment improves over time, for different values of λ (including λ = 0, i.e. original Tacotron2)?

**Comment by efthymisgeo** [comment]
@kmn1024 
- First of all we do not imply that lower loss necessarily means better alignments in general. Loss may degrade due to other reasons too. However, in the context of our work where we experiment with a fixed dataset and training recipe and the only difference is the extra loss term it is safe to conclude that the lower loss is due to the loss addition which in turn assists the alignment of the architecture.
-  The different lambdas look like Fig.1 from the [published paper](https://ieeexplore.ieee.org/stamp/stamp.jsp?arnumber=10023268). We refer you to the zoomed version which is easier to distinguish Tacotron2 vs Regotron
- No we do not have an exhaustive illustration across timesteps. The point of Fig.2 is to illustrate that Regotron for epoch ~200 has better alignment than Tacotron2. The other two lambda values you refer to behave in a similar manner for the LJSpeech dataset.
